task_0:    
    model:
      n_workers: 8
      n_hidden_state: 16
      communication_range: 2
      worker_placement: "random_multidirectional"
      worker_init: "random"
      reward_calculation: "scn2"
      n_oracle_states: 5
      p_oracle_change: 0
      episode_length: 16
      grid_size: 9
task_1:    
    model:
      n_workers: 8
      n_hidden_state: 16
      communication_range: 2
      worker_placement: "random"
      worker_init: "random"
      reward_calculation: "scn2"
      n_oracle_states: 5
      p_oracle_change: 0
      episode_length: 16
      grid_size: 9
task_2:    
    model:
      n_workers: 8
      n_hidden_state: 16
      communication_range: 2
      worker_placement: "random_multidirectional"
      worker_init: "random"
      reward_calculation: "scn2"
      n_oracle_states: 5
      p_oracle_change: 0
      episode_length: 16
      grid_size: 13
task_3:    
    model:
      n_workers: 8
      n_hidden_state: 16
      communication_range: 2
      worker_placement: "random"
      worker_init: "random"
      reward_calculation: "scn2"
      n_oracle_states: 5
      p_oracle_change: 0
      episode_length: 16
      grid_size: 13
task_4:    
    model:
      n_workers: 8
      n_hidden_state: 16
      communication_range: 2
      worker_placement: "random_multidirectional"
      worker_init: "random"
      reward_calculation: "scn2"
      n_oracle_states: 5
      p_oracle_change: 0
      episode_length: 16
      grid_size: 17
task_5:    
    model:
      n_workers: 8
      n_hidden_state: 16
      communication_range: 2
      worker_placement: "random"
      worker_init: "random"
      reward_calculation: "scn2"
      n_oracle_states: 5
      p_oracle_change: 0
      episode_length: 16
      grid_size: 17
task_6:    
    model:
      n_workers: 8
      n_hidden_state: 16
      communication_range: 2
      worker_placement: "random"
      worker_init: "random"
      reward_calculation: "scn2"
      n_oracle_states: 5
      p_oracle_change: 0.3
      episode_length: 64
      grid_size: 21
