task_0:
    model:
      n_workers: 4
      n_hidden_state: 4
      communication_range: 2
      worker_placement: "line_unidirectional"
      worker_init: "uniform"
      reward_calculation: "individual"
      n_oracle_states: 5
      p_oracle_change: 0
      episode_length: 25
      grid_size: 21
