task_0:    
    model:
      n_workers: 4
      n_hidden_state: 16
      communication_range: 2
      worker_placement: "line_multidirectional"
      worker_init: "random"
      reward_calculation: "individual"
      n_oracle_states: 5
      p_oracle_change: 0
      episode_length: 16
      grid_size: 21
task_1:    
    model:
      n_workers: 4
      n_hidden_state: 16
      communication_range: 2
      worker_placement: "random_multidirectional"
      worker_init: "random"
      reward_calculation: "individual"
      n_oracle_states: 5
      p_oracle_change: 0
      episode_length: 16
      grid_size: 21
task_2:    
    model:
      n_workers: 4
      n_hidden_state: 16
      communication_range: 2
      worker_placement: "random_multidirectional"
      worker_init: "random"
      reward_calculation: "individual"
      n_oracle_states: 5
      p_oracle_change: 0.3
      episode_length: 64
      grid_size: 21
