name: swarm
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - cryptography=41.0.3=py311hdda0065_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.11=h7f8727e_2
  - pillow=10.0.1=py311ha6cbd5a_0
  - pip=23.3=py311h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - pytorch=2.1.0=py3.11_cpu_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.1=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - setuptools=68.0.0=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.16.0=py311_cpu
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiosignal==1.3.1
      - anyio==4.0.0
      - appdirs==1.4.4
      - appnope==0.1.3
      - arrow==1.3.0
      - asttokens==2.4.0
      - attrs==23.1.0
      - backcall==0.2.0
      - binaryornot==0.4.4
      - cachetools==5.3.1
      - chardet==5.2.0
      - charset-normalizer==3.3.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - comm==0.1.4
      - contourpy==1.1.1
      - cookiecutter==2.4.0
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - executing==2.0.0
      - farama-notifications==0.0.4
      - fastjsonschema==2.18.1
      - filelock==3.12.4
      - fonttools==4.43.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - gymnasium==0.29.1
      - h11==0.14.0
      - humanize==4.8.0
      - imageio==2.31.6
      - ipykernel==6.25.2
      - ipython==8.16.1
      - ipyvue==1.10.1
      - ipyvuetify==1.8.10
      - ipywidgets==8.1.1
      - jedi==0.19.1
      - joblib==1.3.2
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.4.0
      - jupyter-core==5.4.0
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lz4==4.3.2
      - markdown==3.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mesa==2.1.2
      - mesa-viz-tornado==0.1.1
      - msgpack==1.0.7
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - numpy==1.26.1
      - packaging==23.2
      - pandas==2.1.1
      - parso==0.8.3
      - pathtools==0.1.2
      - pettingzoo==1.24.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.11.0
      - prompt-toolkit==3.0.39
      - protobuf==4.24.4
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==13.0.0
      - pygments==2.16.1
      - pymdown-extensions==10.3
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-slugify==8.0.1
      - pytz==2023.3.post1
      - pyzmq==25.1.1
      - ray==2.7.1
      - reacton==1.7.2
      - referencing==0.30.2
      - rich==13.6.0
      - rich-click==1.7.0
      - rpds-py==0.10.6
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - sentry-sdk==1.32.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - solara==1.22.0
      - stack-data==0.6.3
      - starlette==0.31.1
      - sympy==1.12
      - tensorboardx==2.6.2.2
      - text-unidecode==1.3
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - torch-geometric==2.4.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.11.2
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.0.7
      - uvicorn==0.23.2
      - wandb==0.15.12
      - watchdog==3.0.0
      - wcwidth==0.2.8
      - websockets==11.0.3
      - widgetsnbextension==4.0.9
prefix: /itet-stor/kpius/net_scratch/conda_envs/swarm
